Message {
    channel:
        TextChannel {
            type: 'text',
            deleted: false,
            id: '655972587842830347',
            name: '指令測試區',
            position: 2,
            parentID: '536546022441222165',
            permissionOverwrites:
                Collection [Map] {
                    '536546022441222164' => [PermissionOverwrites],
                    '665018582631186433' => [PermissionOverwrites] 
                },
            topic: null,
            nsfw: false,
            lastMessageID: '697371097351585804',
            lastPinTimestamp: null,
            rateLimitPerUser: 0,
            guild:
                Guild {
                    members: [Collection],
                    channels: [Collection],
                    roles: [Collection],
                    presences: [Collection],
                    deleted: false,
                    available: true,
                    id: '536546022441222164',
                    name: 'Wang Family',
                    icon: 'd2f8a515d9eaf510b866742cab5c8b02',
                    splash: null,
                    region: 'singapore',
                    memberCount: 41,
                    large: false,
                    features: [],
                    applicationID: null,
                    afkTimeout: 300,
                    afkChannelID: null,
                    systemChannelID: '611765081881182208',
                    embedEnabled: undefined,
                    verificationLevel: 0,
                    explicitContentFilter: 0,
                    mfaLevel: 0,
                    joinedTimestamp: 1576573785064,
                    defaultMessageNotifications: 'ALL',
                    ownerID: '536431526280298496',
                    _rawVoiceStates: [Collection],
                    emojis: [Collection] 
                },
            messages: Collection [Map] { '697371097351585804' => [Circular] },
            _typing: Map {} 
        },
    deleted: false,
    id: '697371097351585804',
    type: 'DEFAULT',
    content: '12',
    author:
        User {
            id: '536431526280298496',
            username: '思文',
            discriminator: '6486',
            avatar: 'd3c5104832d819264d6c52d3f638d349',
            bot: false,
            lastMessageID: '697371097351585804',
            lastMessage: [Circular] 
        },
    member:
        GuildMember {
            guild:
                Guild {
                    members: [Collection],
                    channels: [Collection],
                    roles: [Collection],
                    presences: [Collection],
                    deleted: false,
                    available: true,
                    id: '536546022441222164',
                    name: 'Wang Family',
                    icon: 'd2f8a515d9eaf510b866742cab5c8b02',
                    splash: null,
                    region: 'singapore',
                    memberCount: 41,
                    large: false,
                    features: [],
                    applicationID: null,
                    afkTimeout: 300,
                    afkChannelID: null,
                    systemChannelID: '611765081881182208',
                    embedEnabled: undefined,
                    verificationLevel: 0,
                    explicitContentFilter: 0,
                    mfaLevel: 0,
                    joinedTimestamp: 1576573785064,
                    defaultMessageNotifications: 'ALL',
                    ownerID: '536431526280298496',
                    _rawVoiceStates: [Collection],
                    emojis: [Collection] 
                },
            user:
                User {
                    id: '536431526280298496',
                    username: '思文',
                    discriminator: '6486',
                    avatar: 'd3c5104832d819264d6c52d3f638d349',
                    bot: false,
                    lastMessageID: '697371097351585804',
                    lastMessage: [Circular] 
                },
            joinedTimestamp: 1547992940296,
            _roles:
                [ '547427342486601748',
                  '590067077491064832',
                  '665018582631186433' ],
            serverDeaf: false,
            serverMute: false,
            selfMute: undefined,
            selfDeaf: undefined,
            voiceSessionID: undefined,
            voiceChannelID: undefined,
            speaking: false,
            nickname: '詩文',
            lastMessageID: '697371097351585804',
            lastMessage: [Circular],
            deleted: false 
        },
    pinned: false,
    tts: false,
    nonce: '697371103311429632',
    system: false,
    embeds: [],
    attachments: Collection [Map] {},
    createdTimestamp: 1586336626137,
    editedTimestamp: null,
    reactions: Collection [Map] {},
    mentions:
        MessageMentions {
            everyone: false,
            users: Collection [Map] {},
            roles: Collection [Map] {},
            _content: '12',
            _client:
                Client {
                    _events: [Object],
                    _eventsCount: 6,
                    _maxListeners: 10,
                    options: [Object],
                    rest: [RESTManager],
                    dataManager: [ClientDataManager],
                    manager: [ClientManager],
                    ws: [WebSocketManager],
                    resolver: [ClientDataResolver],
                    actions: [ActionsManager],
                    voice: [ClientVoiceManager],
                    shard: null,
                    users: [Collection],
                    guilds: [Collection],
                    channels: [Collection],
                    presences: [Collection],
                    user: [ClientUser],
                    readyAt: 2020-04-08T09:03:34.640Z,
                    broadcasts: [],
                    pings: [Array],
                    _timeouts: [Set],
                    _intervals: [Set] 
                },
            _guild:
                Guild {
                    members: [Collection],
                    channels: [Collection],
                    roles: [Collection],
                    presences: [Collection],
                    deleted: false,
                    available: true,
                    id: '536546022441222164',
                    name: 'Wang Family',
                    icon: 'd2f8a515d9eaf510b866742cab5c8b02',
                    splash: null,
                    region: 'singapore',
                    memberCount: 41,
                    large: false,
                    features: [],
                    applicationID: null,
                    afkTimeout: 300,
                    afkChannelID: null,
                    systemChannelID: '611765081881182208',
                    embedEnabled: undefined,
                    verificationLevel: 0,
                    explicitContentFilter: 0,
                    mfaLevel: 0,
                    joinedTimestamp: 1576573785064,
                    defaultMessageNotifications: 'ALL',
                    ownerID: '536431526280298496',
                    _rawVoiceStates: [Collection],
                    emojis: [Collection] 
                },
            _members: null,
            _channels: null 
        },
    webhookID: null,
    hit: null,
    _edits: [] 
}
