(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var e,f="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},g;if("function"==typeof Object.setPrototypeOf)g=Object.setPrototypeOf;else{var h;a:{var l={C:!0},m={};try{m.__proto__=l;h=m.C;break a}catch(a){}h=!1}g=h?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var n=g,p=this||self,q=function(a,b){function d(){}d.prototype=b.prototype;a.prototype=new d;a.prototype.constructor=a};var r=function(a,b,d){d=void 0===d?null:d;var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,d);b.dispatchEvent(c);return c};var t=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,t);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};q(t,Error);t.prototype.name="CustomError";var u=function(a,b){a=a.split("%s");for(var d="",c=a.length-1,k=0;k<c;k++)d+=a[k]+(k<b.length?b[k]:"%s");t.call(this,d+a[c])};q(u,t);u.prototype.name="AssertionError";var v=function(a,b,d){if(!a){var c="Assertion failed";if(b){c+=": "+b;var k=Array.prototype.slice.call(arguments,2)}throw new u(""+c,k||[]);}return a},w=function(a,b){throw new u("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var z=function(a,b){this.l=a===x&&b||"";this.B=y};z.prototype.g=!0;z.prototype.f=function(){return this.l.toString()};z.prototype.toString=function(){return"SafeUrl{"+this.l+"}"};var A=function(a){if(a instanceof z&&a.constructor===z&&a.B===y)return a.l;var b=typeof a;w("expected object of type SafeUrl, got '"+a+"' of type "+("object"!=b?b:a?Array.isArray(a)?"array":b:"null"));return"type_error:SafeUrl"},B=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,y={},x={};var C=function(){this.j=""};C.prototype.g=!0;C.prototype.f=function(){return this.j};C.prototype.toString=function(){return"SafeStyle{"+this.j+"}"};C.prototype.h=function(a){this.j=a};(new C).h("");var D=function(){this.i=""};D.prototype.g=!0;D.prototype.f=function(){return this.i};D.prototype.toString=function(){return"SafeStyleSheet{"+this.i+"}"};D.prototype.h=function(a){this.i=a};(new D).h("");var E=[],F=function(a){a=E.indexOf(a);0<=a&&E.splice(a,1)};document.addEventListener("click",function(a){for(var b=0;b<E.length;b++)if(25>Math.abs(a.clientX-E[b].D)&&25>Math.abs(a.clientY-E[b].F)||25>Math.abs(a.screenX-E[b].K)&&25>Math.abs(a.screenY-E[b].L))E.splice(b,1),a.stopPropagation(),a.preventDefault()},!0);var G=function(){var a=HTMLElement.call(this)||this;a.v=0;a.A=0;a.c=null;a.o=null;a.b=null;a.m=null;a.s=a.G.bind(a);a.a=!0;return a},H=HTMLElement;G.prototype=f(H.prototype);
G.prototype.constructor=G;if(n)n(G,H);else for(var I in H)if("prototype"!=I)if(Object.defineProperties){var J=Object.getOwnPropertyDescriptor(H,I);J&&Object.defineProperty(G,I,J)}else G[I]=H[I];e=G.prototype;e.connectedCallback=function(){this.b||(this.c=this.u.bind(this),this.o=this.J.bind(this),this.b=this.I.bind(this),this.m=this.H.bind(this));this.addEventListener("click",this.c,!1);this.addEventListener("touchstart",this.o,!1);this.addEventListener("action",this.s,!1)};
e.disconnectedCallback=function(){this.removeEventListener("click",this.c,!1);this.removeEventListener("touchstart",this.o,!1);this.removeEventListener("action",this.s,!1)};e.u=function(a){this.a&&r("action",this,a);this.a=!0};e.J=function(a){this.addEventListener("touchmove",this.b,!1);this.addEventListener("touchend",this.m,!1);a=a.touches[0];this.v=a.clientX;this.A=a.clientY};
e.H=function(a){this.u(a);this.removeEventListener("touchmove",this.b,!1);this.removeEventListener("touchend",this.m,!1);a=a.changedTouches[0];a={D:a.clientX,F:a.clientY,K:a.screenX,L:a.screenY};E.push(a);setTimeout(F.bind(null,a),2500)};e.I=function(a){a=a.touches[0];this.a=this.a&&10>=Math.abs(this.v-a.clientX)&&10>=Math.abs(this.A-a.clientY)};
e.G=function(a){var b=this.getAttribute("exit-id"),d=this.getAttribute("product-index"),c=this.getAttribute("exit-override-url");c&&!r("tapareaexit",this,{"exit-id":b,url:c,"product-index":d,"action-event":a.detail}).detail.handled&&(c instanceof z?a=c:(a=c,a instanceof z||(a="object"==typeof a&&a.g?a.f():String(a),v(B.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez"),a=new z(x,a))),p.open(A(a),"",void 0,void 0))};customElements.define("gwd-taparea",G);}).call(this);
